anchor_version = "0.24.2"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[programs.mainnet]
serum_multisig = "6tbPiQLgTU4ySYWyZGXbnVSAEzLc1uF8t5kJPXXgBmRP"

[programs.devnet]
serum_multisig = "F3Uf5F61dmht1xuNNNkk3jnzj82TY56vVjVEhZALRkN"

[programs.localnet]
serum_multisig = "6tbPiQLgTU4ySYWyZGXbnVSAEzLc1uF8t5kJPXXgBmRP"

[scripts]
test = "npx mocha -t 1000000 tests/"
