anchor_version = "0.26.0"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[programs.mainnet]
mean_multisig = "FF7U7Vj1PpBkTPau7frwLLrUHrjkxTQLsH7U5K3T3B3j"

[programs.devnet]
mean_multisig = "MMSdTDhtwBs2w4MxGCbqfWLgerMQNbXazizghoh7uMJ"

[programs.localnet]
mean_multisig = "MMSdTDhtwBs2w4MxGCbqfWLgerMQNbXazizghoh7uMJ"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/multisig.ts"

[registry]
url = "https://api.apr.dev"
